### ISSUE TITLE
Define project goals

### ISSUE THREAD

**Issue by SolomiiaMatiichuk** [SolomiiaMatiichuk/OpenSpace#2]
Clearly state the objectives and expected outcome of the project. This includes identifying the problem the project aims to solve, defining the goals and objectives of the project, and determining the expected outcomes. Define the target audience, stakeholders, and project constraints. All of these elements should be documented in a project charter or similar document.

**Comment by kubrub** [comment]
https://github.com/SolomiiaMatiichuk/OpenSpace/blob/main/Documents/Project%20goals.pdf

**Comment by SolomiiaMatiichuk** [comment]
Reviewed. LGTM
