### ISSUE TITLE
Develop a project plan

### ISSUE THREAD

**Issue by SolomiiaMatiichuk** [SolomiiaMatiichuk/OpenSpace#3]
a)Develop a project schedule: Create a timeline for the project, including a list of tasks, dependencies, and deadlines. 
b) Allocate resources: Determine the human, financial, and technological resources needed to complete the project. 
c) Establish a budget: Develop a detailed budget that includes all costs associated with the project.

Results: presenting schedule, resources and budget of project (Gantt Chart, Network Diagram or Milestone Chart)

**Comment by kubrub** [comment]
[Documents/Budget.jpg](https://github.com/SolomiiaMatiichuk/OpenSpace/blob/main/Documents/Budget.jpg)
https://github.com/SolomiiaMatiichuk/OpenSpace/blob/main/Documents/Project%20Schedule%20(Gantt%20Chart).jpg

**Comment by IrynaSloboda** [comment]
Reviewed
