### ISSUE TITLE
Gather functional and non-functional requirements - User stories creating

### ISSUE THREAD

**Issue by SolomiiaMatiichuk** [SolomiiaMatiichuk/OpenSpace#4]
Result: list of User stories (more than 50 Use cases)

**Comment by IvannaaTR** [comment]
https://github.com/SolomiiaMatiichuk/OpenSpace/blob/main/Documents/Functional%20and%20non-functional%20requirements.pdf

**Comment by kubrub** [comment]
review, looks good for me
