### ISSUE TITLE
Development UI requirements for the project: wireframes, clickable prototypes, mockups.

### ISSUE THREAD

**Issue by SolomiiaMatiichuk** [SolomiiaMatiichuk/OpenSpace#5]
Results: UI requirements in the form of wireframes, clickable prototypes, Mockups

**Comment by IrynaSloboda** [comment]
[Documents/Figma wireframes, mockups, clickable prototypes.pdf](https://github.com/SolomiiaMatiichuk/OpenSpace/blob/main/Documents/Figma%20wireframes%2C%20mockups%2C%20clickable%20prototypes.pdf)

**Comment by SolomiiaMatiichuk** [comment]
Reviewed - everything good
